// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf175tLGOq9Gc9DM9R50WpOTYe0wsf5o0',
    appId: '1:568005501024:web:5a117a6c993840e8716305',
    messagingSenderId: '568005501024',
    projectId: 'finalproject-5bd6e',
    authDomain: 'finalproject-5bd6e.firebaseapp.com',
    storageBucket: 'finalproject-5bd6e.firebasestorage.app',
    measurementId: 'G-6495LQS6PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpUxNXw59cHWPTrdH4mjVLGSCKwS1_9-g',
    appId: '1:568005501024:android:159bdb5c66f080eb716305',
    messagingSenderId: '568005501024',
    projectId: 'finalproject-5bd6e',
    storageBucket: 'finalproject-5bd6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOchYKYpTsxLnJWbiPeBS_YDzQky3gcU',
    appId: '1:568005501024:ios:395a11f0633610b3716305',
    messagingSenderId: '568005501024',
    projectId: 'finalproject-5bd6e',
    storageBucket: 'finalproject-5bd6e.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );
}
